import type { Metadata } from 'next';
import Link from 'next/link';
import {
  Container,
  MarketingShell,
  Section,
} from '../../../src/components/brand';
import { JsonLd, breadcrumbsSchema } from '../../../src/components/seo';

export const metadata: Metadata = {
  title: 'Terms of service - TinyBooth',
  description:
    'TinyBooth terms of service. Free vs paid features, in-app purchase refunds, content ownership, retention, DMCA, governing law (California).',
  alternates: { canonical: '/legal/terms' },
  robots: { index: true, follow: true },
  openGraph: {
    title: 'Terms of service - TinyBooth',
    description: 'TinyBooth terms of service. Refunds, retention, DMCA, governing law.',
    url: '/legal/terms',
  },
};

/**
 * /legal/terms. terms of service. Real terms covering: free vs paid,
 * IAP refunds, content ownership, retention policy, DMCA contact,
 * disclaimers, governing law (CA, since Camrynn is LA-based).
 */
export default function TermsPage(): JSX.Element {
  return (
    <MarketingShell>
      <JsonLd
        data={breadcrumbsSchema([
          { name: 'TinyBooth', path: '/' },
          { name: 'Legal', path: '/legal/privacy' },
          { name: 'Terms', path: '/legal/terms' },
        ])}
      />

      <Container size="prose">
        <Section eyebrow="Legal" heading="Terms of service">
          <p className="text-graphite text-sm">Last updated: 2026-04-26</p>

          <p className="mt-6 text-graphite leading-relaxed">
            These terms govern your use of TinyBooth, the photo booth app, and TinyWall, the guest
            photo wall, both operated by Camrynn Dilley as a sole proprietor in Los Angeles,
            California. By using either product you agree to these terms. If you do not agree, do
            not use the products.
          </p>

          <h2 className="text-2xl font-bold text-ink mt-10">1. Free and paid features</h2>
          <p className="text-graphite leading-relaxed mt-3">
            The TinyBooth app is free to download and free to use for personal photography. The
            free tier includes a small &ldquo;tinybooth.com&rdquo; wordmark on printed strips and
            on the Instagram-format share. The free TinyWall tier accepts up to 100 guest uploads
            per event with a 7-day retention window. We may change the free tier limits with at
            least 30 days notice posted on this page.
          </p>
          <p className="text-graphite leading-relaxed mt-3">
            Paid features (Strip Unlock, Event Pass, Event Pass Plus) are sold as one-time
            consumable purchases. Each purchase grants the features described on the{' '}
            <Link href="/pricing" className="text-coral underline">
              pricing page
            </Link>{' '}
            for the duration listed there (Event Pass: one event, 60-day retention; Event Pass
            Plus: one event, 90-day retention). There is no recurring subscription at this time.
          </p>

          <h2 className="text-2xl font-bold text-ink mt-10">2. Refunds for in-app purchases</h2>
          <p className="text-graphite leading-relaxed mt-3">
            In-app purchases on iOS and Android are processed by Apple and Google respectively.
            Refund requests for these purchases must be filed through the App Store or Google Play
            Store using their refund flows. We honor any refund issued by either platform and
            adjust the linked event tier accordingly.
          </p>
          <p className="text-graphite leading-relaxed mt-3">
            Web purchases via Stripe (Event Pass at $12.99, Event Pass Plus at $34) are eligible
            for a full refund within 14 days of purchase, provided the event has not yet started.
            Email{' '}
            <a href="mailto:hello@tinybooth.com" className="text-coral underline">
              hello@tinybooth.com
            </a>{' '}
            with your event slug.
          </p>

          <h2 className="text-2xl font-bold text-ink mt-10">3. Content ownership</h2>
          <p className="text-graphite leading-relaxed mt-3">
            You retain full ownership of every photo and video you upload through TinyBooth or
            TinyWall, and of every photo strip generated by the booth app. We do not claim
            ownership of your content. We hold a limited license to store, process, and display
            your content within the product solely to provide the service to you and your event
            guests.
          </p>
          <p className="text-graphite leading-relaxed mt-3">
            For events, the host (the user who created the event) is treated as the owner of the
            event-scoped photos. Guests who upload to a TinyWall event grant the host the right to
            display, download, and redistribute their uploads for the purposes of the event. We
            do not use your content for advertising, training, or resale.
          </p>

          <h2 className="text-2xl font-bold text-ink mt-10">4. Retention</h2>
          <p className="text-graphite leading-relaxed mt-3">
            Photo retention is tied to the event tier:
          </p>
          <ul className="mt-3 space-y-2 text-graphite leading-relaxed pl-6 list-disc">
            <li>Free events: 7 days from the event creation date.</li>
            <li>Event Pass: 60 days from the event end date.</li>
            <li>Event Pass Plus: 90 days from the event end date.</li>
            <li>Standalone TinyBooth strips never reach our servers and stay on your device.</li>
            <li>Bulk-export zip files are deleted 24 hours after generation.</li>
          </ul>
          <p className="text-graphite leading-relaxed mt-3">
            Past the retention window, both database rows and storage objects are deleted by an
            hourly cleanup job. You can extend retention by upgrading to a higher tier or by
            exporting the event as a zip file at any time during retention.
          </p>

          <h2 className="text-2xl font-bold text-ink mt-10">5. Acceptable use</h2>
          <p className="text-graphite leading-relaxed mt-3">
            You agree not to use TinyBooth or TinyWall to upload, display, or distribute content
            that is illegal under California or US federal law, that infringes the copyright or
            other rights of any person, or that constitutes harassment, hate speech, or sexual
            content involving minors. We may remove such content and terminate accounts that post
            it without notice.
          </p>

          <h2 className="text-2xl font-bold text-ink mt-10">6. DMCA / copyright</h2>
          <p className="text-graphite leading-relaxed mt-3">
            If you believe content on TinyBooth or TinyWall infringes your copyright, send a DMCA
            notice to{' '}
            <a href="mailto:dmca@tinybooth.com" className="text-coral underline">
              dmca@tinybooth.com
            </a>{' '}
            including: a physical or electronic signature, identification of the copyrighted work,
            identification of the URL of the infringing material, your contact information, a
            statement of good-faith belief, and a statement under penalty of perjury that you are
            authorized to act on behalf of the copyright owner. We process valid notices within 5
            business days.
          </p>

          <h2 className="text-2xl font-bold text-ink mt-10">7. Disclaimers</h2>
          <p className="text-graphite leading-relaxed mt-3">
            TinyBooth and TinyWall are provided as-is. We make no warranty that the products will
            be uninterrupted, error-free, or that data loss will not occur. Photo booths and
            photo walls are physical events at venues with imperfect Wi-Fi; you are responsible
            for testing the setup before the event and for maintaining a backup plan (camera roll
            saves, manual photographer coverage). We are not liable for missed shots, failed
            uploads, or photo loss caused by venue connectivity, hardware failure, or
            user-initiated deletion.
          </p>

          <h2 className="text-2xl font-bold text-ink mt-10">8. Limitation of liability</h2>
          <p className="text-graphite leading-relaxed mt-3">
            To the fullest extent permitted by law, our total liability for any claim arising out
            of or relating to TinyBooth or TinyWall is limited to the amount you paid us in the
            12 months preceding the claim. We are not liable for indirect, incidental, or
            consequential damages.
          </p>

          <h2 className="text-2xl font-bold text-ink mt-10">9. Termination</h2>
          <p className="text-graphite leading-relaxed mt-3">
            You can stop using TinyBooth or TinyWall at any time. You can delete your account from
            the dashboard at{' '}
            <Link href="/dashboard/account" className="text-coral underline">
              tinybooth.com/dashboard/account
            </Link>{' '}
            or by emailing hello@tinybooth.com. We may suspend or terminate access for violations
            of these terms.
          </p>

          <h2 className="text-2xl font-bold text-ink mt-10">10. Changes to these terms</h2>
          <p className="text-graphite leading-relaxed mt-3">
            We may update these terms. The &ldquo;last updated&rdquo; date at the top will change
            and material changes are announced by email to active hosts. Continued use after the
            effective date constitutes acceptance of the new terms.
          </p>

          <h2 className="text-2xl font-bold text-ink mt-10">11. Governing law</h2>
          <p className="text-graphite leading-relaxed mt-3">
            These terms are governed by the laws of the State of California, US, without regard
            to conflict-of-laws principles. Any dispute arising out of these terms or out of your
            use of the products is subject to the exclusive jurisdiction of the state and federal
            courts located in Los Angeles County, California.
          </p>

          <h2 className="text-2xl font-bold text-ink mt-10">12. Contact</h2>
          <p className="text-graphite leading-relaxed mt-3">
            For anything related to these terms, email{' '}
            <a href="mailto:hello@tinybooth.com" className="text-coral underline">
              hello@tinybooth.com
            </a>
            .
          </p>
        </Section>
      </Container>
    </MarketingShell>
  );
}
